<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Directory.Build.Tool.props" />

  <ItemGroup>
    <ProjectReference Include="..\squad.Agent\squad.Agent.csproj"
                      AdditionalProperties="RuntimeIdentifier=$(RuntimeIdentifier)" />
    <ProjectReference Include="..\squad.Agent.Cli\squad.Agent.Cli.csproj"
                      AdditionalProperties="RuntimeIdentifier=$(RuntimeIdentifier)" />
    <ProjectReference Include="..\squad.Agent.Process\squad.Agent.Process.csproj"
                      AdditionalProperties="RuntimeIdentifier=$(RuntimeIdentifier)" />
  </ItemGroup>
</Project>
