using global::squad.Process;
using global::squad.Configuration;
using global::squad.Handoffs;

namespace squad.Commands;

static class Handoff
{
    static readonly string UsageText = """
        Usage: handoff <draft-file>

        Draft formats:

        type: git_handoff
        to: <role>[,<role>...]
        priority: NN
        task: <short-stable-task-name>
        commit: <10-char-commit-abbrev>

        type: note
        to: <role>[,<role>...]
        priority: NN
        message: <one line, max 80 chars>
        """.ReplaceLineEndings("\n");

    static readonly HashSet<string> ReservedFields = ["id", "from", "role", "recipient", "created_at", "enqueued_at", "dequeued_at", "completed_at"];
    static readonly HashSet<string> AllowedFields = ["type", "to", "priority", "task", "commit", "message"];
    static readonly HashSet<string> AllowedTypes = ["git_handoff", "note"];
    static readonly Dictionary<string, HashSet<string>> AllowedFieldsByType = new()
    {
        ["git_handoff"] = ["type", "to", "priority", "task", "commit"],
        ["note"] = ["type", "to", "priority", "message"],
    };

    public static int Run(string[] args)
    {
        if (args.Length == 0 || args[0] is "-h" or "--help" or "help")
        {
            Console.WriteLine(UsageText);
            return 0;
        }

        if (args.Length != 1)
        {
            Console.Error.WriteLine(UsageText);
            return 1;
        }

        var draft = args[0];
        if (!File.Exists(draft))
        {
            Console.Error.WriteLine($"Draft file not found: {draft}");
            return 1;
        }

        try
        {
            var roleWorktreeRoot = Path.GetFullPath(ProjectRoot.ResolveViaGit());
            var projectRoot = ProjectRoot.ResolveProjectRoot(roleWorktreeRoot);
            var roles = SquadConfig.ReadRoles(projectRoot);
            var sender = CurrentRoleResolver.Resolve(roles, roleWorktreeRoot).Role;

            if (!SquadConfig.RoleKnown(roles, sender))
            {
                Console.Error.WriteLine($"Unknown sender role: {sender}");
                return 1;
            }

            var (headers, ordered, parseErrors) = ParseDraft(draft);
            var (recipients, canonicalCommit, validationErrors) = Validate(headers, ordered, roles);
            var allErrors = parseErrors.Concat(validationErrors).ToList();

            if (allErrors.Count > 0)
            {
                Console.Error.WriteLine($"HANDOFF INVALID: {draft}");
                Console.Error.WriteLine();
                Console.Error.WriteLine("Errors:");
                foreach (var error in allErrors)
                    Console.Error.WriteLine($"- {error}");
                Console.Error.WriteLine();
                Console.Error.WriteLine(UsageText);
                return 2;
            }

            var stateDir = Path.Combine(roleWorktreeRoot, ".blaxquad", "handoffs");
            var outboxFile = WriteHandoff(stateDir, headers, recipients, canonicalCommit, sender);
            File.Delete(draft);
            Console.WriteLine($"HANDOFF QUEUED: {outboxFile}");
            return 0;
        }
        catch (CliExitException ex)
        {
            if (!string.IsNullOrEmpty(ex.Message))
                Console.Error.WriteLine(ex.Message);
            return ex.ExitCode;
        }
    }

    static (Dictionary<string, string> headers, List<string> ordered, List<string> errors) ParseDraft(string draftPath)
    {
        var headers = new Dictionary<string, string>();
        var ordered = new List<string>();
        var errors = new List<string>();
        var bodySeen = false;
        var lineNo = 0;

        foreach (var line in File.ReadAllLines(draftPath))
        {
            lineNo++;

            if (bodySeen)
            {
                if (!string.IsNullOrWhiteSpace(line))
                    errors.Add($"Line {lineNo}: draft handoffs may contain headers only; payloads are generated by handoff.");
                continue;
            }

            if (string.IsNullOrWhiteSpace(line))
            {
                bodySeen = true;
                continue;
            }

            if (!line.Contains(": ", StringComparison.Ordinal))
            {
                errors.Add($"Line {lineNo}: expected 'field: value'.");
                continue;
            }

            var parts = line.Split(": ", 2);
            var field = parts[0];
            var value = parts[1];

            if (string.IsNullOrWhiteSpace(field) || string.IsNullOrWhiteSpace(value))
            {
                errors.Add($"Line {lineNo}: field and value must both be non-empty.");
            }
            else if (ReservedFields.Contains(field))
            {
                errors.Add($"Line {lineNo}: header '{field}' is reserved and must not be written by agents.");
            }
            else if (!AllowedFields.Contains(field))
            {
                errors.Add($"Line {lineNo}: unknown header '{field}'.");
            }
            else if (headers.ContainsKey(field))
            {
                errors.Add($"Line {lineNo}: duplicate header '{field}'.");
            }
            else
            {
                headers[field] = value;
                ordered.Add(field);
            }
        }

        return (headers, ordered, errors);
    }

    static (List<string> recipients, string? canonicalCommit, List<string> errors) Validate(
        Dictionary<string, string> headers, List<string> ordered, IReadOnlyList<RoleRow> roles)
    {
        headers.TryGetValue("type", out var type);
        headers.TryGetValue("to", out var to);
        headers.TryGetValue("priority", out var priority);
        headers.TryGetValue("commit", out var commit);
        headers.TryGetValue("task", out var taskName);
        headers.TryGetValue("message", out var noteMessage);

        var (recipients, recipientErrors) = ValidateRecipients(to, roles);

        var fieldErrors = new List<string>();
        if (!string.IsNullOrEmpty(type))
        {
            var allowedForType = AllowedFieldsByType.GetValueOrDefault(type, []);
            foreach (var field in ordered)
            {
                if (!allowedForType.Contains(field))
                    fieldErrors.Add($"Header '{field}' is not allowed for type '{type}'.");
            }
        }

        var baseErrors = new List<string>();
        if (string.IsNullOrWhiteSpace(type)) baseErrors.Add("Missing required header 'type'.");
        if (string.IsNullOrWhiteSpace(to)) baseErrors.Add("Missing required header 'to'.");
        if (string.IsNullOrWhiteSpace(priority)) baseErrors.Add("Missing required header 'priority'.");
        if (!string.IsNullOrWhiteSpace(type) && !AllowedTypes.Contains(type))
            baseErrors.Add($"Header 'type' must be one of git_handoff or note; got '{type}'.");
        if (!string.IsNullOrWhiteSpace(priority) && !Priority.IsValid(priority))
            baseErrors.Add($"Header 'priority' must be two digits from 00 to 99; got '{priority}'.");

        string? canonical = null;
        string? commitError = null;
        if (type == "git_handoff")
        {
            if (string.IsNullOrWhiteSpace(commit))
                commitError = "Missing required header 'commit' for git_handoff.";
            else if (!System.Text.RegularExpressions.Regex.IsMatch(commit, "^[0-9a-fA-F]{10}$"))
                commitError = $"Header 'commit' must be exactly 10 hexadecimal characters; got '{commit}'.";
            else
                (canonical, commitError) = CanonicalCommit(commit);
        }

        var gitErrors = new List<string>();
        if (type == "git_handoff")
        {
            if (string.IsNullOrWhiteSpace(taskName))
                gitErrors.Add("Missing required header 'task' for git_handoff.");
            else if (taskName.Length > 80)
                gitErrors.Add($"Header 'task' must be no longer than 80 characters; got {taskName.Length}.");
        }
        if (type != "git_handoff" && !string.IsNullOrWhiteSpace(commit))
            gitErrors.Add("Header 'commit' is only allowed for git_handoff.");
        if (type != "git_handoff" && !string.IsNullOrWhiteSpace(taskName))
            gitErrors.Add("Header 'task' is only allowed for git_handoff.");
        if (commitError is not null)
            gitErrors.Add(commitError);

        var noteErrors = new List<string>();
        if (type == "note")
        {
            if (string.IsNullOrWhiteSpace(noteMessage))
                noteErrors.Add("Missing required header 'message' for note.");
            else if (noteMessage.Length > 80)
                noteErrors.Add($"Header 'message' must be no longer than 80 characters; got {noteMessage.Length}.");
        }
        if (type != "note" && !string.IsNullOrWhiteSpace(noteMessage))
            noteErrors.Add("Header 'message' is only allowed for note.");

        var allErrors = baseErrors.Concat(recipientErrors).Concat(fieldErrors).Concat(gitErrors).Concat(noteErrors).ToList();
        return (recipients, canonical, allErrors);
    }

    static (List<string> recipients, List<string> errors) ValidateRecipients(string? to, IReadOnlyList<RoleRow> roles)
    {
        if (string.IsNullOrWhiteSpace(to))
            return ([], []);

        var recipients = to.Split(',');
        var errors = new List<string>();
        var seen = new HashSet<string>();
        foreach (var recipient in recipients)
        {
            if (string.IsNullOrWhiteSpace(recipient))
                errors.Add("Header 'to' contains an empty recipient.");
            if (recipient.Contains('_'))
                errors.Add($"Recipient role '{recipient}' is invalid; role names may not contain underscores.");
            if (seen.Contains(recipient))
                errors.Add($"Duplicate recipient '{recipient}'.");
            if (!string.IsNullOrWhiteSpace(recipient) && !SquadConfig.RoleKnown(roles, recipient))
                errors.Add($"Unknown recipient role '{recipient}'.");
            seen.Add(recipient);
        }
        return (recipients.ToList(), errors);
    }

    static (string? canonical, string? error) CanonicalCommit(string commit)
    {
        var disambiguate = ProcessRunner.Run("git", ["rev-parse", $"--disambiguate={commit}"]);
        var matches = SplitLinesLikeJava(disambiguate.StdOut);
        if (matches.Length != 1)
            return (null, $"Header 'commit' must resolve to exactly one Git object; '{commit}' matched {matches.Length}.");

        var obj = matches[0];
        var objectType = ProcessRunner.Run("git", ["cat-file", "-t", obj]).StdOut.Trim();
        if (objectType != "commit")
            return (null, $"Header 'commit' must resolve to a commit; '{commit}' resolves to '{objectType}'.");

        var canonical = ProcessRunner.Run("git", ["rev-parse", "--short=10", obj]).StdOut.Trim();
        return (canonical, null);
    }

    static string[] SplitLinesLikeJava(string s)
    {
        if (s.Length == 0)
            return [""];
        var parts = System.Text.RegularExpressions.Regex.Split(s, "\r\n|\n|\r");
        var end = parts.Length;
        while (end > 0 && parts[end - 1].Length == 0)
            end--;
        return parts[..end];
    }

    static string WriteHandoff(string stateDir, Dictionary<string, string> headers, List<string> recipients, string? canonicalCommit, string sender)
    {
        var timestampId = Timestamps.IdNow();
        var createdAt = Timestamps.Now();
        var sequence = SequenceCounter.Next(stateDir);
        var id = $"{timestampId}_{sequence}_from_{sender}";
        var recipientSlug = string.Join("_", recipients);
        var priority = headers["priority"];
        var type = headers["type"];
        var filename = $"{priority}_{timestampId}_{sequence}_from_{sender}_to_{recipientSlug}.handoff";

        var outboxDir = Path.Combine(stateDir, "outbox");
        var tmpDir = Path.Combine(outboxDir, "tmp");
        var tmpFile = Path.Combine(tmpDir, $"{filename}.tmp");
        var outboxFile = Path.Combine(outboxDir, filename);

        var handoffBody = type switch
        {
            "git_handoff" => $"merge_and_process {sender} {canonicalCommit}",
            "note" => headers.GetValueOrDefault("message", ""),
            _ => "",
        };

        var lines = new List<string>
        {
            $"id: {id}",
            $"from: {sender}",
            $"to: {string.Join(",", recipients)}",
            $"priority: {priority}",
            $"type: {type}",
        };
        if (type == "git_handoff")
        {
            lines.Add($"role: {sender}");
            lines.Add($"task: {headers["task"]}");
            lines.Add($"commit: {canonicalCommit}");
        }
        else if (type == "note")
        {
            lines.Add($"message: {headers["message"]}");
        }
        lines.Add($"created_at: {createdAt}");
        lines.Add("");
        lines.Add(handoffBody);

        Directory.CreateDirectory(tmpDir);
        Directory.CreateDirectory(outboxDir);
        Directory.CreateDirectory(Path.Combine(stateDir, "sent"));
        Directory.CreateDirectory(Path.Combine(stateDir, "failed"));

        File.WriteAllText(tmpFile, string.Join("\n", lines) + "\n");
        File.Move(tmpFile, outboxFile);
        return outboxFile;
    }
}



