<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\squad.Domain\squad.Domain.csproj" />
    <ProjectReference Include="..\squad.Ui.Abstractions\squad.Ui.Abstractions.csproj" />
    <ProjectReference Include="..\squad.Process\squad.Process.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.2.1" />
  </ItemGroup>

</Project>
