<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\squad.AgentProvider.Abstractions\squad.AgentProvider.Abstractions.csproj" />
    <ProjectReference Include="..\squad.Configuration\squad.Configuration.csproj" />
    <ProjectReference Include="..\squad.Process\squad.Process.csproj" />
  </ItemGroup>

</Project>
